name: Build and Test App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-test-app:
    name: Build and test app
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install Packages
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Start App
      run: npm run start &
    
    - name: Run Unit Tests
      run: npm run test:unit
    
    - name: Display SoftUni Username
      run: echo 'geo.dimitrov'
    
    - name: Run UI Tests
      run: npm run test:ui

  deploy-app:
    runs-on: ubuntu-latest
    needs: build-and-test-app

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Deploy App To Render
      uses: JorgeLNJunior/render-deploy@v1.4.4

      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        clear_cache: true
        wait_deploy: true
